"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { ArrowRight, CalendarDays, MapPin, Sparkles, Users, Gamepad2, Search } from "lucide-react";
import Header from "@/components/Header";
import Nav from "@/components/Nav";
import GameCard,{Game} from "@/components/GameCard";
const categories=["🎲 Društvene igre","🃏 Karte","♟️ Strategija","🎉 Party igre","🎮 Gaming"];
export default function Home(){const[games,setGames]=useState<Game[]>([]);useEffect(()=>{fetch('/api/games').then(r=>r.json()).then(d=>setGames(d.games||[])).catch(()=>{})},[]);return <div className="web-layout"><Nav/><main className="main-content"><Header/><section className="web-hero"><div className="hero-copy"><span className="eyebrow"><Sparkles size={15}/> IGRAJ VIŠE, DOGOVARAJ MANJE</span><h1>Ekipa za igru je bliže nego što misliš.</h1><p>Otkrij partije u blizini, upoznaj nove ljude i popuni prazno mjesto za stolom.</p><div className="hero-actions"><Link href="/games" className="btn inline"><Search size={18}/> Pronađi igru</Link><Link href="/create" className="btn secondary inline"><Gamepad2 size={18}/> Organiziraj igru</Link></div><div className="trust-row"><span><Users size={17}/><b>1.240+</b> igrača</span><span><CalendarDays size={17}/><b>86</b> igara ovaj tjedan</span><span><MapPin size={17}/><b>12</b> gradova</span></div></div><div className="hero-visual"><div className="floating-card card-a"><span>🎲</span><b>Catan večeras</b><small>Još 2 mjesta · Zagreb</small></div><div className="floating-card card-b"><span>🃏</span><b>Bela u kvartu</b><small>Još 1 igrač · Karlovac</small></div><div className="hero-orbit"><div>EK</div><div>IPS</div></div></div></section><section className="content-section"><div className="section-title"><div><span className="section-kicker">ISTRAŽI</span><h2>Što ti se igra?</h2></div><Link href="/games">Sve kategorije <ArrowRight size={16}/></Link></div><div className="category-grid">{categories.map(x=><Link href="/games" key={x}>{x}<ArrowRight size={17}/></Link>)}</div></section><section className="content-section"><div className="section-title"><div><span className="section-kicker">U TVOM GRADU</span><h2>Nadolazeće igre</h2></div><Link href="/games">Pogledaj sve <ArrowRight size={16}/></Link></div><div className="game-grid">{games.slice(0,6).map(g=><GameCard key={g.id} game={g}/>)}{!games.length&&<div className="empty wide"><Users size={42}/><h3>Prva igra tek čeka domaćina</h3><p>Objavi što želiš igrati i pronađi ekipu.</p><Link className="btn inline" href="/create">Organiziraj igru</Link></div>}</div></section></main></div>}
